#!/bin/bash

cd "$(dirname "$0")"

USER=$(cat .env | grep 'USER' | cut -d '=' -f2 | xargs)
PASS=$(cat .env | grep 'PASSWORD' | cut -d '=' -f2 | xargs)
SLACK_WEBHOOK=$(cat .env | grep 'SLACK_WEBHOOK' | cut -d '=' -f2 | xargs)
OPENVPN_FILE=$(cat .env | grep 'OPENVPN_FILE' | cut -d '=' -f2 | xargs)

TIMEOUT=10
PERCENT_TARGET=80

if [[ -z "$USER" || -z "$PASS" || -z "$SLACK_WEBHOOK" || -z "$OPENVPN_FILE" ]]; then
    echo "Error, provide a valid USER, PASSWORD and SLACK WEBHOOK"
    exit 1
fi


echo "Execution in: $(date '+%Y-%m-%d %H:%M:%S')"

echo "Checking openvpn executation"
if [ -z "$(pgrep openvpn)" ]; then
    echo "OpenVpn are not in executation, starting..."
    sudo openvpn "$OPENVPN_FILE" &> /dev/null &
else
    echo "OpenVpn already started"
fi

echo "Starting SBCs storage verification..."

for i in {0..1}
do
    for j in {1..255}
    do
        echo "- Testing 10.8.$i.$j"

        result=$(timeout $TIMEOUT sshpass -p $PASS ssh -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null $USER@10.8.$i.$j df -h 2>/dev/null \
          | grep "/mm" | head -n1 | awk '{print $5}')

        if [ "$result" != "" ]; then
            if [ ${result%?} -gt $PERCENT_TARGET ]; then
              MESSAGE="{\"text\":\":warning:Warning!\n\nClient *10.8.$i.$j*, has *$result* of storage\"}"
              echo "  - Warning! Client 10.8.$i.$j, has $result of storage"

              curl -X POST -H 'Content-type: application/json' --data "$MESSAGE" $SLACK_WEBHOOK
            fi
        fi
    done
done

echo "Finished!"
